### ISSUE TITLE
node errors in Karma window

### ISSUE THREAD

**Issue by rajivsavroop** [lele85/karma-electron-launcher-simple-seed#1]
after npm test my Karma window console shows me these errors

Uncaught ReferenceError: exports is not defined  boot.js:15
Uncaught ReferenceError: jasmineRequire is not defined adapter.js:323 
Uncaught ReferenceError: jasmine is not defined CalcSpec.js:1 
Uncaught ReferenceError: describe is not defined debug.html:42 
Uncaught TypeError: this.start is not a function

any Idea whats going on?

**Comment by denisgursky** [comment]
@rajivsavroop , https://github.com/jasmine/jasmine/issues/964

**Comment by rajivsavroop** [comment]
thanks @denisgursky
